kind: pipeline
type: docker
name: greeting

environment:
  GREETING_EN: hello

steps:
  - name: en
    image: alpine
    commands:
    - echo $GREETING_EN
    - echo world

  - name: es
    image: alpine
    commands:
    - echo hola
    - echo world
  
  - name: es-angry-person
    image: alpine
    commands:
    - echo hola
    - echo motherfucker
  
  - name: es-very-angry-person
    image: alpine
    commands:
    - echo hola
    - echo motherfucker I is angry now
  
  - name: es-very-angry-person-more
    image: alpine
    commands:
    - echo hola
    - echo motherfucker I is angry now-I can tell you
